
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/markeep?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분


jwt:
  secret: 

logging.level:
  org.hibernate.SQL: debug


